
const ROOT='/ElektroX – Elektro Hauska', KEY='elektrox_v5';
let db=JSON.parse(localStorage.getItem(KEY)||'null')||{customers:[],articles:[],docs:[],counters:{offer:0,invoice:0}};
let cur=null,eid=null,accessToken=localStorage.getItem('elektrox_dropbox_token')||'',pkceVerifier=localStorage.getItem('elektrox_pkce')||'';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const eur=n=>Number(n||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
const persist=()=>localStorage.setItem(KEY,JSON.stringify(db));
const cfgKey='elektrox_app_key'; const getAppKey=()=>localStorage.getItem(cfgKey)||'';
function redirect(){return location.origin+location.pathname} function setStatus(ok,msg){dbStatus.className='status '+(ok?'ok':'warn');dbStatus.textContent=ok?'☁️ '+msg:'☁️ '+msg;settingsStatus.className='status '+(ok?'ok':'warn');settingsStatus.textContent=msg}
function show(id){document.querySelectorAll('main>section').forEach(x=>x.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');if(id==='home')home();if(id==='customers')renderCustomers();if(id==='articles')renderArticles();if(id==='docs')renderDocs();if(id==='settings'){appKey.value=getAppKey();redirectUri.value=redirect();setStatus(!!accessToken,accessToken?'Dropbox verbunden':'Nicht verbunden')}}
function home(){cc.textContent=db.customers.length+' Kunden';ac.textContent=db.articles.length+' Artikel';dc.textContent=db.docs.length+' Dokumente';setStatus(!!accessToken,accessToken?'Dropbox verbunden':'Dropbox nicht verbunden')}
function next(t){db.counters[t]=(db.counters[t]||0)+1;return(t==='offer'?'ANG':'RE')+'-'+new Date().getFullYear()+'-'+String(db.counters[t]).padStart(4,'0')}
async function sha256(s){let b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function rand(){let a=new Uint8Array(64);crypto.getRandomValues(a);return btoa(String.fromCharCode(...a)).replace(/[^0-9A-Za-z\-._~]/g,'').slice(0,64)}
async function connectDropbox(){let key=appKey.value.trim();if(!key){alert('Bitte zuerst den Dropbox App Key eintragen.');return}localStorage.setItem(cfgKey,key);pkceVerifier=rand();localStorage.setItem('elektrox_pkce',pkceVerifier);let ch=await sha256(pkceVerifier);let state=rand();localStorage.setItem('elektrox_oauth_state',state);let u='https://www.dropbox.com/oauth2/authorize?client_id='+encodeURIComponent(key)+'&response_type=code&token_access_type=online&redirect_uri='+encodeURIComponent(redirect())+'&code_challenge='+encodeURIComponent(ch)+'&code_challenge_method=S256&state='+encodeURIComponent(state);location.href=u}
async function finishOAuth(){let p=new URLSearchParams(location.search);let code=p.get('code'),state=p.get('state');if(!code)return;if(state!==localStorage.getItem('elektrox_oauth_state')){alert('OAuth-State stimmt nicht.');return}let key=getAppKey(),body=new URLSearchParams({code,grant_type:'authorization_code',client_id:key,redirect_uri:redirect(),code_verifier:pkceVerifier});let r=await fetch('https://api.dropboxapi.com/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});let j=await r.json();if(!r.ok){alert('Dropbox-Anmeldung fehlgeschlagen: '+(j.error_description||j.error||'unbekannter Fehler'));return}accessToken=j.access_token;localStorage.setItem('elektrox_dropbox_token',accessToken);history.replaceState({},'',redirect());setStatus(true,'Dropbox verbunden');await syncAll()}
async function dbx(path,body,upload=false){if(!accessToken)throw Error('Nicht mit Dropbox verbunden');let headers={'Authorization':'Bearer '+accessToken,'Content-Type':upload?'application/octet-stream':'application/json'};if(upload)headers['Dropbox-API-Arg']=JSON.stringify(body.arg);let r=await fetch('https://content.dropboxapi.com/2/'+path,{method:'POST',headers,body:upload?body.data:JSON.stringify(body)});let t=await r.text();let j;try{j=JSON.parse(t)}catch{j=t}if(!r.ok)throw Error(j?.error_summary||j?.error||t);return j}
async function uploadJSON(path,obj){let data=new TextEncoder().encode(JSON.stringify(obj,null,2));return dbx('files/upload',{arg:{path,mode:{'.tag':'overwrite'},autorename:false,mute:true},data},true)}
async function syncAll(){if(!accessToken)return;try{for(const c of db.customers)await uploadJSON(ROOT+'/Kunden/'+safe(c.id)+'.json',c);for(const a of db.articles)await uploadJSON(ROOT+'/Artikel & Leistungen/'+safe(a.id)+'.json',a);for(const d of db.docs)await uploadJSON(ROOT+'/'+(d.type==='offer'?'Angebote':'Rechnungen')+'/'+safe(d.number)+'.json',d);setStatus(true,'Dropbox synchronisiert')}catch(e){setStatus(false,'Dropbox-Fehler');console.error(e)}}
function safe(s){return String(s).replace(/[^A-Za-z0-9._-]/g,'_')}
function disconnectDropbox(){accessToken='';localStorage.removeItem('elektrox_dropbox_token');show('settings')}
async function saveToDropbox(){await syncAll()}
function newDoc(type,cid=''){let c=db.customers.find(x=>x.id===cid);cur={id:crypto.randomUUID(),type,number:next(type),date:new Date().toISOString().slice(0,10),customerId:cid,customerName:c?.name||'',street:c?.street||'',zip:c?.zip||'',city:c?.city||'',email:c?.email||'',items:[],notes:type==='invoice'?'Zahlbar innerhalb von 14 Tagen.':''};renderEditor();show('editor')}
function renderEditor(){let d=cur;ed.innerHTML=`<h2>${d.type==='offer'?'Angebot':'Rechnung'} ${esc(d.number)}</h2><label>Datum</label><input id="date" type="date" value="${esc(d.date)}"><label>Kunde</label><select id="cust" onchange="pick(this.value)"><option value="">— Kunde wählen —</option>${db.customers.map(c=>`<option value="${c.id}" ${c.id===d.customerId?'selected':''}>${esc(c.name)}</option>`).join('')}</select><label>Straße</label><input id="street" value="${esc(d.street)}"><div class="row"><div><label>PLZ</label><input id="zip" value="${esc(d.zip)}"></div><div><label>Ort</label><input id="city" value="${esc(d.city)}"></div></div><label>Artikel/Leistung</label><select id="art"><option value="">— auswählen —</option>${db.articles.map(a=>`<option value="${a.id}">${esc(a.name)} · ${eur(a.price)}</option>`).join('')}</select><button class="secondary" style="margin-top:7px" onclick="add()">＋ Position</button><div id="items"></div><label>Bemerkung / Zahlungsziel</label><textarea id="notes" rows="3">${esc(d.notes)}</textarea><div class="panel" style="background:#fafafa;margin-top:12px"><div id="tot"></div></div><div class="row" style="margin-top:12px"><button class="secondary" onclick="pdf('${d.id}')">PDF / Drucken</button><button class="yellow" onclick="saveDoc();setTimeout(()=>mail('${d.id}'),150)">E-Mail</button></div>`;renderItems()}
function pick(id){let c=db.customers.find(x=>x.id===id);if(!c)return;Object.assign(cur,{customerId:id,customerName:c.name,street:c.street,zip:c.zip,city:c.city,email:c.email});street.value=c.street;zip.value=c.zip;city.value=c.city}
function add(){let a=db.articles.find(x=>x.id===art.value);if(!a)return;cur.items.push({name:a.name,unit:a.unit||'Stk.',qty:1,price:+(a.vk??a.price)||0,ek:+(a.ek??0)||0,articleNumber:a.number||''});renderItems()}
function renderItems(){items.innerHTML=cur.items.map((x,i)=>`<div class="item"><div class="row"><div style="flex:2"><label>Bezeichnung</label><input value="${esc(x.name)}" onchange="cur.items[${i}].name=this.value"></div><div><label>Menge</label><input type="number" value="${x.qty}" onchange="cur.items[${i}].qty=+this.value;renderItems()"></div><div><label>Preis netto</label><input type="number" step=".01" value="${x.price}" onchange="cur.items[${i}].price=+this.value;renderItems()"></div></div><button class="secondary" onclick="cur.items.splice(${i},1);renderItems()">Entfernen</button></div>`).join('')||'<p class="muted">Noch keine Positionen.</p>';let n=cur.items.reduce((s,x)=>s+x.qty*x.price,0),v=n*.19;tot.innerHTML=`Netto: <b>${eur(n)}</b><br>19 % MwSt.: <b>${eur(v)}</b><br><span class="total">Gesamt: ${eur(n+v)}</span>`}
async function saveDoc(){cur.date=date.value;cur.street=street.value;cur.zip=zip.value;cur.city=city.value;cur.notes=notes.value;let i=db.docs.findIndex(x=>x.id===cur.id);if(i<0)db.docs.push(structuredClone(cur));else db.docs[i]=structuredClone(cur);persist();if(accessToken)await saveToDropbox();show('docs')}
function renderDocs(){let q=(ds.value||'').toLowerCase();dl.innerHTML=db.docs.slice().reverse().filter(d=>(d.number+' '+d.customerName).toLowerCase().includes(q)).map(d=>`<div class="item"><b>${esc(d.number)}</b> · ${d.type==='offer'?'Angebot':'Rechnung'}<br><span class="muted">${esc(d.customerName||'Ohne Kunde')} · ${esc(d.date)}</span><div class="row" style="margin-top:7px"><button onclick="openDoc('${d.id}')">Öffnen</button><button class="secondary" onclick="pdf('${d.id}')">PDF</button>${d.email?`<button class="yellow" onclick="mail('${d.id}')">E-Mail</button>`:''}${d.type==='offer'?`<button class="yellow" onclick="invoice('${d.id}')">→ Rechnung</button>`:''}</div></div>`).join('')||'<p class="muted">Keine Dokumente.</p>'}
function openDoc(id){cur=structuredClone(db.docs.find(x=>x.id===id));renderEditor();show('editor')}
async function invoice(id){let o=db.docs.find(x=>x.id===id);cur=structuredClone(o);cur.id=crypto.randomUUID();cur.type='invoice';cur.number=next('invoice');cur.date=new Date().toISOString().slice(0,10);cur.notes='Zahlbar innerhalb von 14 Tagen.';db.docs.push(structuredClone(cur));persist();if(accessToken)await saveToDropbox();openDoc(cur.id)}
function editCustomer(id=''){eid=id;let c=db.customers.find(x=>x.id===id)||{};ceb.innerHTML=`<h2>${id?'Kunde bearbeiten':'Neuer Kunde'}</h2><label>Name/Firma</label><input id="cn" value="${esc(c.name)}"><label>Straße</label><input id="cst" value="${esc(c.street)}"><div class="row"><div><label>PLZ</label><input id="cz" value="${esc(c.zip)}"></div><div><label>Ort</label><input id="ci" value="${esc(c.city)}"></div></div><label>E-Mail</label><input id="ce" type="email" value="${esc(c.email)}"><label>Telefon</label><input id="cp" value="${esc(c.phone)}">`;show('ce')}
async function saveCustomer(){let c={id:eid||crypto.randomUUID(),name:cn.value,street:cst.value,zip:cz.value,city:ci.value,email:ce.value,phone:cp.value};let i=db.customers.findIndex(x=>x.id===c.id);if(i<0)db.customers.push(c);else db.customers[i]=c;persist();if(accessToken)await saveToDropbox();show('customers')}
function renderCustomers(){let q=(cs.value||'').toLowerCase();cl.innerHTML=db.customers.filter(c=>(c.name+' '+c.city+' '+c.email).toLowerCase().includes(q)).map(c=>`<div class="item"><b>${esc(c.name)}</b><br><span class="muted">${esc(c.street)} · ${esc(c.zip)} ${esc(c.city)} · ${esc(c.email)}</span><div class="row" style="margin-top:7px"><button class="secondary" onclick="editCustomer('${c.id}')">Bearbeiten</button><button onclick="newDoc('offer','${c.id}')">Angebot</button></div></div>`).join('')||'<p class="muted">Noch keine Kunden.</p>'}
function editArticle(id=''){eid=id;let a=db.articles.find(x=>x.id===id)||{};aeb.innerHTML=`<h2>${id?'Artikel bearbeiten':'Neuer Artikel'}</h2><label>Bezeichnung</label><input id="an" value="${esc(a.name)}"><label>Artikelnummer</label><input id="anum" value="${esc(a.number)}"><div class="row"><div><label>Einheit</label><input id="au" value="${esc(a.unit||'Stk.')}"></div><div><label>Einkaufspreis netto</label><input id="aek" type="number" step=".01" value="${a.ek??a.price??0}"></div></div><div class="row"><div><label>Kalkulation %</label><input id="am" type="number" step=".1" value="${a.markup??23}"></div><div><label>Verkaufspreis netto</label><input id="avk" type="number" step=".01" value="${a.vk??(((a.ek??a.price??0)*(1+(a.markup??23)/100)).toFixed(2))}"></div></div><p class="muted">DATANORM-Artikel können hier nach dem Import angepasst werden.</p>`;show('ae')}
async function saveArticle(){let ek=+aek.value||0, markup=+am.value||0, vk=+avk.value||+(ek*(1+markup/100)); let a={id:eid||crypto.randomUUID(),name:an.value,number:anum.value,unit:au.value||'Stk.',ek,markup,vk,price:vk};let i=db.articles.findIndex(x=>x.id===a.id);if(i<0)db.articles.push(a);else db.articles[i]=a;persist();if(accessToken)await saveToDropbox();show('articles')}
async function importDatanorm(file){
  if(!file)return;
  const text=await file.text();
  const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());
  const rows=lines.map((line,i)=>{const f=line.split(';');return {i:i+1,type:(f[0]||'').trim(),fields:f.map(x=>x.trim())}});
  const articleRows=rows.filter(r=>/^[Aa]$/.test(r.type));
  const version=rows.find(r=>/^[Vv]$/.test(r.type));
  if(!articleRows.length){alert('Keine A-Artikelsätze erkannt. Bitte eine DATANORM-Artikeldatei (4/5) auswählen.');return;}
  dnPanel.classList.remove('hidden');
  const sample=articleRows.slice(0,8);
  dnPanel.innerHTML=`<h3>DATANORM-Import</h3><p class="muted">${esc(file.name)} · ${articleRows.length} Artikelsätze${version?' · Vorlaufsatz erkannt':''}</p><p>ElektroX hat die DATANORM-Datei gelesen. Da Großhändler die Felder unterschiedlich nutzen können, prüfst du vor dem Import die Zuordnung.</p><div class="row"><div><label>Artikelnummer-Feld</label><select id="dnNum">${fieldOptions(sample,'number')}</select></div><div><label>Bezeichnung-Feld</label><select id="dnName">${fieldOptions(sample,'name')}</select></div></div><div class="row"><div><label>Einkaufspreis-Feld</label><select id="dnPrice">${fieldOptions(sample,'price')}</select></div><div><label>Mengeneinheit-Feld</label><select id="dnUnit">${fieldOptions(sample,'unit')}</select></div></div><div class="panel" style="background:#fafafa;overflow:auto"><table><thead><tr><th>Satz</th><th>Vorschau</th></tr></thead><tbody>${sample.map(r=>`<tr><td>${r.i}</td><td><small>${esc(r.fields.slice(0,10).join(' · '))}</small></td></tr>`).join('')}</tbody></table></div><div class="row"><button class="primary" onclick='confirmDatanormImport()'>${articleRows.length} Artikel importieren</button><button class="secondary" onclick="dnPanel.classList.add('hidden')">Abbrechen</button></div>`;
  window._dnRows=articleRows; window._dnFile=file.name;
}
function fieldOptions(sample,kind){
  const max=Math.max(...sample.map(r=>r.fields.length)); let opts='';
  for(let i=1;i<max;i++){
    const vals=sample.map(r=>r.fields[i]||'').filter(Boolean); if(!vals.length)continue;
    const joined=vals.slice(0,3).join(' | '); let score=0;
    if(kind==='number')score=vals.filter(v=>/[A-Za-z0-9]/.test(v)&&v.length>=3&&!/^[-+]?\d+[.,]?\d*$/.test(v)).length;
    if(kind==='name')score=vals.filter(v=>v.length>10&&!/^[-+]?\d+[.,]?\d*$/.test(v)).length;
    if(kind==='price')score=vals.filter(v=>{let n=parseFloat(v.replace(',','.'));return isFinite(n)&&n>0&&n<100000}).length;
    if(kind==='unit')score=vals.filter(v=>/^(Stk?\.?|m|kg|h|Set|Paar|VE|Pack|l|m²|m³)$/i.test(v)).length;
    opts+=`<option value="${i}" ${score===Math.max(0, ...sample.map(()=>0))?'':''}>Feld ${i} · ${esc(joined.slice(0,70))}</option>`;
  }
  return opts;
}
function guessField(rows,kind){let max=Math.max(...rows.map(r=>r.fields.length)),best=1,bscore=-1;for(let i=1;i<max;i++){let vals=rows.map(r=>r.fields[i]||'').filter(Boolean),score=0;if(kind==='number')score=vals.filter(v=>/[A-Za-z0-9]/.test(v)&&v.length>=3&&!/^[-+]?\d+[.,]?\d*$/.test(v)).length;if(kind==='name')score=vals.filter(v=>v.length>10&&!/^[-+]?\d+[.,]?\d*$/.test(v)).length;if(kind==='price')score=vals.filter(v=>{let n=parseFloat(v.replace(',','.'));return isFinite(n)&&n>0&&n<100000}).length;if(kind==='unit')score=vals.filter(v=>/^(Stk?\.?|m|kg|h|Set|Paar|VE|Pack|l|m²|m³)$/i.test(v)).length;if(score>bscore){bscore=score;best=i}}return best}
async function confirmDatanormImport(){
  const rows=window._dnRows||[]; const ni=+dnNum.value, na=+dnName.value, pi=+dnPrice.value, ui=+dnUnit.value; let added=0,updated=0;
  for(const r of rows){const number=(r.fields[ni]||'').trim();const name=(r.fields[na]||'').trim();let price=parseFloat(String(r.fields[pi]||'').replace(/[^0-9,.-]/g,'').replace(',','.'));const unit=(r.fields[ui]||'Stk.').trim()||'Stk.';if(!number&&!name)continue;if(!isFinite(price))price=0;let a=db.articles.find(x=>x.number&&number&&x.number===number);if(a){Object.assign(a,{name:name||a.name,price,unit,source:'DATANORM',sourceFile:window._dnFile});updated++}else{db.articles.push({id:crypto.randomUUID(),name:name||number,number,unit,price,source:'DATANORM',sourceFile:window._dnFile});added++}}
  persist();if(accessToken)await saveToDropbox();dnPanel.innerHTML=`<h3>Import abgeschlossen ✅</h3><p>${added} neue Artikel, ${updated} bestehende Artikel aktualisiert.</p><p class="muted">Die Einkaufspreise wurden in ElektroX als EK gespeichert. Die Verkaufskalkulation kann als nächster Schritt darauf aufbauen.</p><button class="primary" onclick="dnPanel.classList.add('hidden');renderArticles()">Fertig</button>`;renderArticles();
}
function renderArticles(){let q=(as.value||'').toLowerCase();al.innerHTML=db.articles.filter(a=>(a.name+' '+a.number).toLowerCase().includes(q)).map(a=>`<div class="item"><b>${esc(a.name)}</b><br><span class="muted">${esc(a.number)} · ${eur(a.price)} / ${esc(a.unit)}</span><button class="secondary" style="float:right" onclick="editArticle('${a.id}')">Bearbeiten</button></div>`).join('')||'<p class="muted">Noch keine Artikel.</p>'}
function docHTML(d){let n=d.items.reduce((s,x)=>s+x.qty*x.price,0),v=n*.19,t=n+v;return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(d.number)}</title><style>body{font-family:Arial;margin:42px;color:#111}header{display:flex;justify-content:space-between;border-bottom:4px solid #ffd400;padding-bottom:15px}h1{font-size:30px;margin:0 0 5px}table{width:100%;border-collapse:collapse;margin-top:30px}th,td{padding:9px;border-bottom:1px solid #ddd;text-align:left}th:last-child,td:last-child{text-align:right}.right{text-align:right}.total{font-size:20px;font-weight:bold}.foot{margin-top:50px;font-size:12px;color:#666}</style></head><body><header><div><h1>ELEKTRO<span style="color:#ffd400">X</span></h1><b>Elektro Hauska</b><br>Blumenstraße 11 · 83734 Hausham<br>0170 4429029 · Elektro.Hauska@gmx.de</div><div><h1>${d.type==='offer'?'ANGEBOT':'RECHNUNG'}</h1>Nr. ${esc(d.number)}<br>Datum: ${esc(d.date)}</div></header><h3>${esc(d.customerName)}</h3>${esc(d.street)}<br>${esc(d.zip)} ${esc(d.city)}<table><tr><th>Beschreibung</th><th>Menge</th><th>Einheit</th><th>Einzelpreis</th><th>Gesamt</th></tr>${d.items.map(x=>`<tr><td>${esc(x.name)}</td><td>${x.qty}</td><td>${esc(x.unit)}</td><td>${eur(x.price)}</td><td>${eur(x.qty*x.price)}</td></tr>`).join('')}</table><div class="right">Netto: ${eur(n)}<br>19 % MwSt.: ${eur(v)}<br><span class="total">Gesamt: ${eur(t)}</span></div><p style="margin-top:30px">${esc(d.notes||'')}</p><div class="foot">Steuernummer: 139/226/30059 · Elektro Hauska · Blumenstraße 11 · 83734 Hausham<br>Bankverbindung: Raiffeisenbank im Oberland · IBAN/BIC aus den Firmeneinstellungen</div></body></html>`}
function pdf(id){let d=db.docs.find(x=>x.id===id),w=window.open('','_blank');w.document.write(docHTML(d)+'<script>window.onload=()=>window.print()<\/script>');w.document.close()}
function mail(id){let d=db.docs.find(x=>x.id===id);if(!d?.email){alert('Beim Kunden ist keine E-Mail-Adresse hinterlegt.');return}let subject=encodeURIComponent((d.type==='offer'?'Angebot ':'Rechnung ')+d.number+' – Elektro Hauska');let body=encodeURIComponent('Guten Tag '+(d.customerName||'')+',\\n\\nanbei erhalten Sie '+(d.type==='offer'?'unser Angebot':'unsere Rechnung')+' '+d.number+'.\\n\\nMit freundlichen Grüßen\\nElektro Hauska');location.href=`mailto:${encodeURIComponent(d.email)}?subject=${subject}&body=${body}`}
redirectUri.value=redirect();home();finishOAuth();
